image:
  file: .gitpod.Dockerfile
ports:
  - port: 8787
    onOpen: open-browser
tasks:
  - init: echo "R_LIBS_USER=/home/gitpod/libs" >> /home/gitpod/.Renviron
  - command: /usr/lib/rstudio-server/bin/rstudio-server --server-user start
